;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC etcdserverpb.Lease Client Implementation
;;;----------------------------------------------------------------------------------
(ns etcd3-clojure.lib.etcdserverpb.Lease.client
  (:require [etcd3-clojure.lib.etcdserverpb :refer :all]
            [etcd3-clojure.lib.authpb :as authpb]
            [etcd3-clojure.lib.mvccpb :as mvccpb]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn LeaseGrant
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "etcdserverpb.Lease"
              :method  "LeaseGrant"
              :input   {:f etcd3-clojure.lib.etcdserverpb/new-LeaseGrantRequest :ch input}
              :output  {:f etcd3-clojure.lib.etcdserverpb/pb->LeaseGrantResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

(defn LeaseRevoke
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "etcdserverpb.Lease"
              :method  "LeaseRevoke"
              :input   {:f etcd3-clojure.lib.etcdserverpb/new-LeaseRevokeRequest :ch input}
              :output  {:f etcd3-clojure.lib.etcdserverpb/pb->LeaseRevokeResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

(defn LeaseKeepAlive
  [client params reply]
  (let [desc {:service "etcdserverpb.Lease"
              :method  "LeaseKeepAlive"
              :input   {:f etcd3-clojure.lib.etcdserverpb/new-LeaseKeepAliveRequest :ch params}
              :output  {:f etcd3-clojure.lib.etcdserverpb/pb->LeaseKeepAliveResponse :ch reply}}]
    (grpc/invoke client desc)))

(defn LeaseTimeToLive
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "etcdserverpb.Lease"
              :method  "LeaseTimeToLive"
              :input   {:f etcd3-clojure.lib.etcdserverpb/new-LeaseTimeToLiveRequest :ch input}
              :output  {:f etcd3-clojure.lib.etcdserverpb/pb->LeaseTimeToLiveResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

