;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC lockpb.Lock Client Implementation
;;;----------------------------------------------------------------------------------
(ns etcd3-clojure.lib.lockpb.Lock.client
  (:require [etcd3-clojure.lib.lockpb :refer :all]
            [etcd3-clojure.lib.etcdserverpb :as etcdserverpb]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn Lock
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "lockpb.Lock"
              :method  "Lock"
              :input   {:f lockpb/new-LockRequest :ch input}
              :output  {:f lockpb/pb->LockResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

(defn Unlock
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "lockpb.Lock"
              :method  "Unlock"
              :input   {:f lockpb/new-UnlockRequest :ch input}
              :output  {:f lockpb/pb->UnlockResponse :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

